- intercept: KEY_CAPSLOCK
  ontap: KEY_ESC
  onhold: KEY_LEFTCTRL

# this is a layer. hold space (onhold) contains several remappings
- intercept: KEY_RIGHTALT
  onhold:

  # special chars
  - from: KEY_E
    to: KEY_ESC

  # vim home row
  - {from: KEY_H, to: KEY_LEFT}
  - {from: KEY_J, to: KEY_DOWN}
  - {from: KEY_K, to: KEY_UP}
  - {from: KEY_L, to: KEY_RIGHT}

  # vim above home row
  - {from: KEY_I, to: KEY_HOME}
  - {from: KEY_Y, to: KEY_PAGEDOWN}
  - {from: KEY_U, to: KEY_PAGEUP}
  - {from: KEY_O, to: KEY_END}

  # xf86 audio
  - {from: KEY_M, to: KEY_MUTE}
  - {from: KEY_COMMA, to: KEY_VOLUMEDOWN}
  - {from: KEY_DOT, to: KEY_VOLUMEUP}

