import = [
  # "~/.config/alacritty/catppuccin-latte.toml",
  "~/.config/alacritty/andromeda.toml",
  # "~/.config/alacritty/github-light.toml",
]

[env]
term = "xterm-256color"

[shell]
program = "/bin/zsh"


[font]
normal = { family = "Berkeley Mono Nerd Font", style = "Regular" }
size = 15

[window]
startup_mode = "Maximized"
